### ISSUE TITLE
[Feature] Add ability to choose ports through command line arguments

### ISSUE THREAD

**Issue by alextarasov1** [Comcast/RestfulHttpsProxy#5]
## Problem
Right now, ports are hardcoded to be `9999` for proxy and `9998` for exposed API.
This should be configurable because sometimes these ports might already be in use.

## Feature Description
Add ability to choose ports through command line arguments. This applies for both the proxy and exposed api. It should be possible to configure both ports independently.

## Additional Context
Dockerfile needs to be updated to account for these changes, as well as the makefile.

**Comment by Silvyre** [comment]
I'd be willing to give this a go!

**Comment by alextarasov1** [comment]
Hello @Silvyre,
Thank you for showing interest!
If you decide to make a pull request, I won't be able to review it until I get back from vacation on October 18 2019.

**Comment by Silvyre** [comment]
Hi, Alex. Thank you for letting me know!
